# Generated by Django 3.0.9 on 2020-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='계정 활성'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=True, verbose_name='스태프'),
        ),
    ]
