# Generated by Django 3.0.9 on 2020-09-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='제목')),
                ('video', models.URLField(unique=True, verbose_name='강의출처')),
                ('description', models.TextField(blank=True, verbose_name='강의설명')),
                ('lecturer', models.CharField(blank=True, max_length=50, verbose_name='강사')),
                ('main_category', models.CharField(blank=True, choices=[('코딩', '코딩'), ('미술', '미술'), ('디자인/편집', '디자인/편집')], max_length=16, verbose_name='대분류')),
                ('sub_category', models.CharField(blank=True, choices=[('Python', 'Python'), ('HTML/CSS', 'HTML/CSS'), ('Javascript', 'Javascript'), ('C', 'C'), ('Java', 'Java'), ('Git', 'Git'), ('연필', '연필'), ('디지털드로잉', '디지털드로잉'), ('색연필', '색연필'), ('수채화', '수채화'), ('펜', '펜'), ('캘리그래피', '캘리그래피'), ('아크릴', '아크릴'), ('Premiere Pro', 'Premiere Pro'), ('Photoshop', 'Photoshop'), ('After Effect', 'After Effect'), ('InDesign', 'InDesign'), ('Illustrator', 'Illustrator'), ('Sketch', 'Sketch')], max_length=18, verbose_name='중분류')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
                'ordering': ['title'],
            },
        ),
    ]
