# Generated by Django 3.0.9 on 2020-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
